services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

  ai-agent-ta:
    build:
      context: .
      dockerfile: Dockerfile-no-ollama
    depends_on:
      - qdrant
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      QDRANT_CLUSTER_URL: http://qdrant:6333
      OLLAMA_BASE_URL: http://host.docker.internal:11434  # ← access Ollama from host
    stdin_open: true
    tty: true

volumes:
  qdrant-data:
